spring:
  application:
    name: mycloud-config-server
  cloud:
    config:  
      server:
        git:
          uri: file://C:\Users\adiaz\Documents\proyecto_test\mycloud-config-server
server:          
  port: 9999